services:
  registry:
    build:
      context: ./registry
    ports:
      - "5100:5000"
    restart: "always"
    volumes:
      - data:/var/lib/registry
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/v2/_catalog"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  data:
