services:
  registry:
    build:
      context: ./registry
    ports:
      - "${REGISTRY_PORT:-5100}:5000"
    restart: "always"
    volumes:
      - data:/var/lib/registry
    networks:
      - private_network
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/v2/_catalog"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_PORT_SSL:-443}:443"
    volumes:
      - ./certs:/certs
    networks:
      - public_network
      - private_network
    restart: "always"
    healthcheck:
      test: ["CMD", "curl", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  public_network:
  private_network:

volumes:
  data:
