services:
  registry:
    build:
      context: ./registry
    ports:
      - "${REGISTRY_PORT:-5100}:5000"
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    restart: "always"
    volumes:
      - data:/var/lib/registry
      - ${CERTS_PATH:-./certs}:/certs
    networks:
      - private_network
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/v2/_catalog"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - registry
    networks:
      - public_network
      - private_network
    restart: "always"
    healthcheck:
      test: ["CMD", "curl", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  public_network:
  private_network:

volumes:
  data:
